FROM oven/bun:1.3-alpine
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

COPY package.json bun.lock* ./
RUN bun install

COPY . .

EXPOSE 3000
CMD ["bun", "run", "dev"]
